{% set name = "markdown-code-runner" %}
{% set version = "2.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3c495998a437bc7d7a4b1a5ce518bce10cf5ba0fa69c569fee1e32c5238603c4

build:
  noarch: python
  entry_points:
    - markdown-code-runner = markdown_code_runner:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - markdown_code_runner
  commands:
    - pip check
    - markdown-code-runner --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/basnijholt/markdown-code-runner
  summary: Automatically execute code blocks within a Markdown file and update the output in-place
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
