{% set name = "markdown-code-runner" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/markdown-code-runner-{{ version }}.tar.gz
  sha256: 35e8435d0c01ebaf2661261ec2079ee9edc52a4b3cc165fb5f2b674c0cdb1e98

build:
  noarch: python
  entry_points:
    - markdown-code-runner = markdown_code_runner:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=42
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.7
    - typing-extensions

test:
  imports:
    - markdown_code_runner
  commands:
    - pip check
    - markdown-code-runner --help
  requires:
    - pip

about:
  home: https://github.com/basnijholt/markdown-code-runner
  summary: Automatically execute code blocks within a Markdown file and update the output in-place
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
